import React, { useState, useEffect } from "react";
import axios from "axios";
import "../styles/About.css";
import jad from "../images/jad.jpeg";
import dylan from "../images/dylan.jpg";

function About() {
  return (
    <div className="app">
      <h2>What is so special? How does it work?</h2>
      <p>
        This program begins by using a{" "}
        <span class="bold" className="highlight">large language model</span> (GPT-2) to generate a
        random sentence.
        <br />
        <br />
        <span class="example">
          Example: sentence = “The quick brown fox jumps over the lazy dog.”
        </span>
        <br />
        <br />
        The <span class="bold" className="highlight">SHA-256 hashing function</span> is then used to
        convert the randomly generated sentence into a hexadecimal hash.
        <br />
        <br />
        <span class="example">
          sha256(sentence) =
          f4202e836541f6ec4d62db7f4f1a3e28148ee8d8de566d7b069ff67f13518a69
        </span>
        <br />
        <br />
        The hexadecimal hash is converted into a decimal value, shortened to
        nine digits, and stored.
        <br />
        <br />
        <span class="example">
          f4202e836541f6ec4d62db7f4f1a3e28148ee8d8de566d7b069ff67f13518a69 →
          950041331
        </span>
        <br />
        <br />A second random number is generated by fetching{" "}
        <span class="bold" className="highlight">atmospheric noise</span> data from a weather API and
        stored.
        <br />
        <br />
        <span class="example">weather API → 93071470</span>
        <br />
        <br />
        The two stored values are XOR’d and the modulo operation is used on the
        result based on the user’s desired range.
        <br />
        <br />
        <span class="example">
          950041331 ^ 93071470 = 1019265921
          <br />
          <br />
          User wants a random number from [1, 100].
          <br />
          <br />
          true random number = (1019265921 % 100) + 1 ={" "}
          <span class="bold">22</span>
        </span>
      </p>

      <h2 className="dev-title">Developers</h2>
      <div className="developers">
        <div className="dev">
          <img className="jad-pic" src={jad}></img>
          <h3>Jad El Idrissi Dafali 🇲🇦</h3>
        </div>
        <div className="dev">
          <img className="dylan-pic" src={dylan}></img>
          <h3>Dylan Tran 🇺🇸</h3>
        </div>
      </div>
    </div>
  );
}

export default About;
